@host = http://localhost:5000

###
POST {{host}}/api/usuarios/login
Content-Type: application/json

{
    "correo": "juan@gmail.com",
    "password": "123456"
}


###
GET {{host}}/api/usuarios
###
POST {{host}}/api/usuarios
Content-Type: application/json

{
    "nombre" : "Juan Gomez Ibarra",   
    "correo": "Juancho15@gmail.com",
    "telefono": "3186788999",
    "password": "123456"
}
###
PUT {{host}}/api/usuarios/1
Content-Type: application/json

{
    "nombre" : "Juan Perez",
    "correo": "JuanchoPerez@gmail.com",
    "telefono": "3186788967"
}

###
DELETE {{host}}/api/usuarios/1