@host = http://localhost:5000
###
GET {{host}}/api/usuarios


###
POST {{host}}/api/usuarios
Content-Type: application/json

{
    "nombre" : "Maria Padilla Bedoya",   
    "correo": "MariPadilla@gmail.com",
    "telefono": "3165436341",
    "password": "260608"
}


###
PUT {{host}}/api/usuarios/8
Content-Type: application/json

{
    "nombre" : "Juan Gomez Ibarra",
    "correo": "JuanchitoIbarra@gmail.com",
    "telefono": "3186778990",
    "password": "310295"
}

###
DELETE {{host}}/api/usuarios/8